# Generated by Django 6.0.7 on 2026-08-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='accounts.inspector', verbose_name='Assigned DPWH Field Inspector'),
        ),
        migrations.AddField(
            model_name='project',
            name='geofence_radius',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Acceptable geofence radius in meters', max_digits=8),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude Coordinate (e.g., 14.6502)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Physical Site Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude Coordinate (e.g., 121.0494)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Current Progress (%)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Allocated Budget (₱)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Assigned Contractor Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(choices=[('District I', 'District I — Caloocan'), ('District II', 'District II — Marikina'), ('District III', 'District III — Valenzuela'), ('District IV', 'District IV — Quezon City')], max_length=50, verbose_name='District / Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Suspended', 'Suspended')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
