# Generated by Django 6.0.7 on 2026-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_assigned_inspector_project_geofence_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='district',
            field=models.CharField(choices=[('LDN 1st DEO', 'Lanao del Norte 1st DEO (Iligan City Area)'), ('LDN 2nd DEO', 'Lanao del Norte 2nd DEO (Tubod Area)'), ('Region X RO', 'DPWH Region X Regional Office (Northern Mindanao)')], max_length=50, verbose_name='District / Jurisdiction'),
        ),
    ]
