# Generated by Django 6.0.7 on 2026-08-02 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(choices=[('District I', 'District I — Caloocan'), ('District II', 'District II — Marikina'), ('District III', 'District III — Valenzuela'), ('District IV', 'District IV — Quezon City')], max_length=50)),
                ('position', models.CharField(default='Field Inspector', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
    ]
