# Generated by Django 6.0.7 on 2026-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='district',
            field=models.CharField(choices=[('LDN 1st DEO', 'Lanao del Norte 1st DEO (Iligan City Area)'), ('LDN 2nd DEO', 'Lanao del Norte 2nd DEO (Tubod Area)'), ('Region X RO', 'DPWH Region X Regional Office (Northern Mindanao)')], max_length=50),
        ),
    ]
