# Generated by Django 6.0.7 on 2026-08-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationreport',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Inspection report', 'verbose_name_plural': 'Inspection reports'},
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='accomplishment_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verification_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('target_entity', models.CharField(max_length=100)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='inspection_images/%Y/%m/%d/')),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('perceptual_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('captured_at', models.DateTimeField()),
                ('geofence_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geofence_status', models.CharField(choices=[('Unknown', 'Unknown'), ('Inside', 'Inside'), ('Outside', 'Outside')], default='Unknown', max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='verifications.verificationreport')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chaincode_name', models.CharField(blank=True, max_length=100)),
                ('commit_status', models.CharField(choices=[('Pending', 'Pending'), ('Committed', 'Committed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='verifications.inspectionimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
