# Generated by Django 6.0.7 on 2026-09-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_alter_verificationreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationreport',
            name='resubmission_of',
            field=models.ForeignKey(blank=True, help_text='Rejected report that this report replaces.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resubmissions', to='verifications.verificationreport'),
        ),
    ]
