# Generated by Django 6.0.7 on 2026-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0003_verificationreport_resubmission_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffChainImageStorage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('perceptual_hash', models.CharField(max_length=64)),
                ('storage_uri', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('geofence_status', models.CharField(max_length=20)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'off_chain_image_storage',
                'ordering': ['-captured_at'],
                'managed': False,
            },
        ),
    ]
